# Generated by Django 4.1.4 on 2023-01-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_date_file",
                    models.FileField(upload_to="conversion/", verbose_name="ファイル"),
                ),
            ],
        ),
    ]
